name: Professor Jekyll Teaches You to Blog Like a Hacker
pygments: true

baseurl: /professorjekyll

course:
  title: Intro to Hacking
  number: Jekyll 101
  instructor: Prof. Jekyll
  
authors:
  einstein:
      name: Albert Einstein
      prof: true
      gravatar: 
      website: http://www.relativity.com
      github: 
      twitter:
      about:  Albert Einstein discovered that E=mc^2.  
  wittgenstein:
      name: Ludwig Wittgenstein
      prof: true
      gravatar:
      website: http://www.tractatus.com
      github:
      twitter:
      about:  Ludwig Wittgenstein discovered that the meaning of E=mc^2 is its use.  
  mccarthy:
      name: John McCarthy
      prof: true
      website: http://common-lisp.net/
      about: John McCarthy invented LISP.  Use it.  
  jdoe:
      name: John Doe
      prof: false
      about: John Doe gets very strange test emails all the time.
  squw:
      name: Suzie Q
      prof: false
      about: Suzie Q once dated John Fogerty.
